installer: attempt to fix blosc issue on new macos

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,9 +2,80 @@
 
 VERSION="0.0.6-SNAPSHOT"
 INSTALL_DIR=${1:-$(pwd)}
+FIJI_DIR=${2:-""}
+
+buildN5Script() {
+
+    mainClass="$1"
+    scriptName="$2"
+    JNA=${3:-""}
+
+    echo '#!/bin/bash' > $scriptName
+    echo '' >> $scriptName
+    echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> $scriptName
+    echo 'java \' >> $scriptName
+    if [[ ! -z $JNA ]]; then echo $JNA; fi >> $scriptName
+    echo "  -Xmx${MEM}g \\" >> $scriptName
+    if [[ $(java -version 2>&1 | grep version) =~ 1.8 ]]
+        then
+            echo '  -XX:+UseConcMarkSweepGC \' >> $scriptName
+    fi
+    echo -n '  -cp $JAR:' >> $scriptName
+    echo -n $(cat cp.txt) >> $scriptName
+    echo ' \' >> $scriptName
+    echo "  $mainClass  \"\$@\"" >> $scriptName
+
+}
+
+hasHomebrewBlosc() {
+
+    hasBrew=$(command -v brew)
+    if [ ! -z $hasBrew ]
+    then
+        brew search c-blosc
+        hasBlosc="$?"
+        if [[ $hasBlosc == "0" ]]
+        then
+            echo "success"
+            #tmp=$(brew --cellar c-blosc)
+            cellarPath=$(dirname $(brew --cellar c-blosc))
+            RESULTPATH=$(dirname $(find $cellarPath -name 'libblosc*'))
+        else
+            echo "c-blosc not found, install with:"
+            echo "  brew install c-blosc"
+        fi
+    else
+        echo "no homebrew found"
+    fi
+}
+
+
+hasCondaBlosc () {
+
+    hasConda=$(command -v conda)
+    if [ ! -z $hasConda ]
+    then
+        echo "conda found"
+        echo "checking for blosc"
+        conda info | grep 'active environment'
+        condaHasBlosc=$(conda list | grep blosc)
+        if [[ ! -z $condaHasBlosc ]]
+        then
+            echo "success"
+            RESULTPATH=$(conda info | grep 'active env location' | sed 's/.*:\s*//g')
+        else
+            echo "blosc not found, install with:"
+            echo "  conda install blosc"
+        fi
+    else
+        echo "no conda found"
+    fi
+}
+
 
 echo "Installing into $INSTALL_DIR"
 
+isMac12="0"
 # check for operating system
 if [[ "$OSTYPE" == "linux-gnu" ]]; then
   echo "Assuming on Linux operating system"
@@ -15,83 +86,67 @@ elif [[ "$OSTYPE" == "darwin"* ]]; then
   # sysctl returns total hardware memory size in bytes
   MEM=$(sysctl hw.memsize | grep hw.memsize | sed s/hw.memsize://g)
   MEM=$(($MEM/2/1024/1024/1024))
+
+  macosVer=$(sw_vers | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
+  if [[ $macosVer =~ ^12\..* ]]
+  then
+    isMac12="1"
+  fi
+
 else
   echo "ERROR - Operating system (arg2) must be either linux or osx - EXITING"
   exit
 fi
+
+JNA_LINE=""
+## Locate blosc on mac12
+if [[ $isMac12 == "1" ]]
+then
+    echo "looking"
+
+    if [[ ! -z $FIJI_DIR ]];
+    then
+        JNA_LINE="-Djna.library.path=\"${FIJI_DIR}/lib/macosx\""
+    else
+        hasHomebrewBlosc
+        if [[ ! -z $RESULTPATH ]]
+        then
+            JNA_LINE="-Djna.library.path=\"${RESULTPATH}\""
+        else
+            hasCondaBlosc
+            if [[ ! -z $RESULTPATH ]]
+            then
+                JNA_LINE="-Djna.library.path=\"${RESULTPATH}\""
+            fi
+        fi
+    fi
+fi
+
+echo $JNA_LINE
+
 
 # mvn clean install
 # temporary workaround for openjdk plus surefire bug
 _JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn clean install
 mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath
 
-echo '#!/bin/bash' > n5-view
-echo '' >> n5-view
-echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-view
-echo 'java \' >> n5-view
-echo "  -Xmx${MEM}g \\" >> n5-view
-if [[ $(java -version 2>&1 | grep version) =~ 1.8 ]]
-	then
-		echo '  -XX:+UseConcMarkSweepGC \' >> n5-view
-fi
-echo -n '  -cp $JAR:' >> n5-view
-echo -n $(cat cp.txt) >> n5-view
-echo ' \' >> n5-view
-echo '  org.janelia.saalfeldlab.View "$@"' >> n5-view
-
+buildN5Script 'org.janelia.saalfeldlab.View' n5-view
 chmod a+x n5-view
 
-echo '#!/bin/bash' > n5-view-cosem
-echo '' >> n5-view-cosem
-echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-view-cosem
-echo 'java \' >> n5-view-cosem
-echo "  -Xmx${MEM}g \\" >> n5-view-cosem
-if [[ $(java -version 2>&1 | grep version) =~ 1.8 ]]
-	then
-		echo '  -XX:+UseConcMarkSweepGC \' >> n5-view
-fi
-echo -n '  -cp $JAR:' >> n5-view-cosem
-echo -n $(cat cp.txt) >> n5-view-cosem
-echo ' \' >> n5-view-cosem
-echo '  org.janelia.saalfeldlab.cosem.ViewCosem "$@"' >> n5-view-cosem
-
+buildN5Script 'org.janelia.saalfeldlab.cosem.ViewCosem' n5-view-cosem
 chmod a+x n5-view-cosem
 
-echo '#!/bin/bash' > n5-copy
-echo '' >> n5-copy
-echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-copy
-echo 'java \' >> n5-copy
-echo "  -Xmx${MEM}g \\" >> n5-copy
-if [[ $(java -version 2>&1 | grep version) =~ 1.8 ]]
-	then
-		echo '  -XX:+UseConcMarkSweepGC \' >> n5-view
-fi
-echo -n '  -cp $JAR:' >> n5-copy
-echo -n $(cat cp.txt) >> n5-copy
-echo ' \' >> n5-copy
-echo '  org.janelia.saalfeldlab.Copy "$@"' >> n5-copy
-
+buildN5Script 'org.janelia.saalfeldlab.Copy' n5-copy
 chmod a+x n5-copy
 
-echo '#!/bin/bash' > n5-equals
-echo '' >> n5-equals
-echo "JAR=\$HOME/.m2/repository/org/janelia/saalfeldlab/n5-utils/${VERSION}/n5-utils-${VERSION}.jar" >> n5-equals
-echo 'java \' >> n5-equals
-echo "  -Xmx${MEM}g \\" >> n5-equals
-if [[ $(java -version 2>&1 | grep version) =~ 1.8 ]]
-	then
-		echo '  -XX:+UseConcMarkSweepGC \' >> n5-view
-fi
-echo -n '  -cp $JAR:' >> n5-equals
-echo -n $(cat cp.txt) >> n5-equals
-echo ' \' >> n5-equals
-echo '  org.janelia.saalfeldlab.Equals "$@"' >> n5-equals
-
+buildN5Script 'org.janelia.saalfeldlab.Equals' n5-equals
 chmod a+x n5-equals
+
 rm cp.txt
 
 mkdir -p $INSTALL_DIR
 mv n5-view $INSTALL_DIR/
+mv n5-view-cosem $INSTALL_DIR/
 mv n5-copy $INSTALL_DIR/
 mv n5-equals $INSTALL_DIR/
 
